spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/litemall_db
    username: root
    password: hao@0829
    type: com.alibaba.druid.pool.DruidDataSource
